/**
 * Central cat easter-egg configuration.
 * Fast peek defaults — short pauses, partial reveals, any direction.
 */
export const catConfig = {
  heroPeek: {
    id: 'heroPeek',
    type: 'peek',
    pose: 'peek',
    direction: 'bottom',
    size: 56,
    interactive: true,
    mobile: 'hide',
    peekDuration: 0.4,
    hideDuration: 0.32,
    visiblePause: [0.9, 1.5],
    hiddenPause: [2.5, 4.5],
    startDelay: [0.6, 1.5],
  },
  scrollReveal: {
    id: 'scrollReveal',
    type: 'scrollReveal',
    pose: 'peek',
    direction: 'bottom',
    size: 48,
    interactive: false,
    mobile: 'static',
    peekDuration: 0.4,
    hideDuration: 0.32,
    visiblePause: [0.9, 1.5],
    hiddenPause: [2.8, 4.8],
  },
  edgeIdle: {
    id: 'edgeIdle',
    type: 'peek',
    pose: 'peek',
    direction: 'top',
    size: 44,
    interactive: false,
    mobile: 'hide',
    peekDuration: 0.38,
    hideDuration: 0.3,
    visiblePause: [0.7, 1.3],
    hiddenPause: [2.4, 4.2],
    startDelay: [1, 2],
  },
  sidePeek: {
    id: 'sidePeek',
    type: 'peek',
    pose: 'peek',
    direction: 'left',
    size: 46,
    interactive: false,
    mobile: 'hide',
    peekDuration: 0.38,
    hideDuration: 0.3,
    visiblePause: [0.8, 1.4],
    hiddenPause: [2.6, 4.6],
    startDelay: [1.2, 2.4],
  },
  aboutTail: {
    id: 'aboutTail',
    type: 'tailFlick',
    pose: 'tail',
    direction: 'right',
    size: 42,
    interactive: false,
    mobile: 'hide',
    peekDuration: 0.3,
    hideDuration: 0.26,
    visiblePause: [0.5, 1],
    hiddenPause: [2.2, 4],
    startDelay: [1.5, 3],
  },
  projectPeek: {
    id: 'projectPeek',
    type: 'hoverPeek',
    pose: 'peek',
    direction: 'bottom',
    size: 48,
    interactive: false,
    mobile: 'hide',
    peekDuration: 0.38,
    hideDuration: 0.3,
  },
  contactTail: {
    id: 'contactTail',
    type: 'tailFlick',
    pose: 'tail',
    direction: 'bottom',
    size: 40,
    interactive: false,
    mobile: 'hide',
    peekDuration: 0.3,
    hideDuration: 0.26,
    visiblePause: [0.45, 0.9],
    hiddenPause: [2.5, 4.5],
    startDelay: [1, 2.5],
  },
};

export const CAT_IDS = Object.keys(catConfig);
